### ISSUE TITLE
Overflow sending packets

### ISSUE THREAD

**Issue by zz85** [seeyarh/xdpsock#8]
when I'm running dev_to_dev with `--n-pkts=1000000` over a physical interface, I'm seeing this error

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/xsk/tx.rs:183:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'failed to join tx/rx handle: Any', examples/dev_to_dev.rs:221:23
```

**Comment by zz85** [comment]
failure seems to be happening after the 4095 packet

**Comment by zz85** [comment]
interesting, I realized goes away running in release builds, rust checks for bound in debug modes and allow wrap around in release

**Comment by zz85** [comment]
one solution might be to change

```rs
            let start = if self.tx_cursor == 0 {
            self.tx_frames.len() - self.cur_batch_size
        } else {
            self.tx_cursor - self.cur_batch_size
        };

        let end = if self.tx_cursor == 0 {
            self.tx_frames.len()
        } else {
            self.tx_cursor
        };
```

**Comment by seeyarh** [comment]
Thanks! Good find! Will take a look in the next two days.
